site_name: Digitale Plattformen

nav:
  - "Home": "index.md"
  - "keycloak": "Anleitungen-initial_login.md"
  - "Webuntis": "Anleitungen-webuntis.md"
  - "Moodle": "Anleitungen-moodle.md"
  - "Nextcloud": "Anleitungen-nextcloud.md"
  - "Beamer/Dongle": "Anleitungen-beamer.md"
  - "Hilfe": "faq.md"
  - "zurück zur Homepage": "https://luisen-gymnasium.de"


theme:
  name: 'material'
  language: de
  logo: images/logo.svg
  favicon: images/favicon.png
  font: false
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        # icon: material/toggle-switch-off-outline
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        # icon: material/toggle-switch
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

  - toc:
      permalink: true

extra:
  consent:
    title: Cookie consent
    description: >- 
      Es könnte sein, dass diese Seite Cookies verwendet. Sollte es so sein, hab ich sie übersehen.

extra_css: [extra.css]

plugins:
  - search
  # - mermaid2

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 